name: Run e2e tests on minikube

on:
  pull_request:
    paths:
      - "deploy/**"
      - "curiefense/**"
      - "e2e/**"
      - ".github/workflows/e2e-tests.yml"

jobs:
  e2e-minikube:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.0
        with:
          driver: docker
          minikube version: 'v1.17.1'
          kubernetes version: 'v1.19.2'
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: "--memory='3Gi' --addons=ingress"

      - name: Interact with the cluster
        run: |
            export BASEDIR=$(git rev-parse --show-toplevel)
            export VERSION=$(git rev-parse --short=12 HEAD)

            # Deploy all services: istio, curiefense, and echoserver (test app)
            deploy/deploy-ci.sh

            echo "-- Install curieconfctl --"

            python3 -m venv "$BASEDIR/venv"
            source "$BASEDIR/venv/bin/activate"
            pip install -U requests pytest pytest-html wheel

            pushd "curiefense/curieconf/utils"
            pip install -e .
            popd

            pushd "curiefense/curieconf/client"
            pip install -e .
            popd

            echo "-- Run e2e tests --"
            pushd e2e

            # TODO(flaper87): Work on enabling full e2e
            # tests.
            IP=$(minikube ip)
            pytest --log-level INFO --base-protected-url http://$IP:30081 --base-conf-url http://$IP:30000/api/v1/ --base-ui-url http://$IP:30080 --elasticsearch-url http://$IP:9200/ --junit-xml pytest.xml -k 'not (test_ipv4 or test_wafsig or test_ratelimit_scope_ipv4_include or test_ratelimit_scope_ipv4_exclude or test_ratelimit_scope_country_include or test_ratelimit_scope_country_exclude or test_ratelimit_scope_company_include or test_ratelimit_scope_company_exclude or test_ratelimit_scope_provider_include or test_ratelimit_scope_provider_exclude or test_ratelimit_countby_ipv4 or test_ratelimit_countby_provider or test_ratelimit_countby_company or test_ratelimit_countby_country or test_ratelimit_event_ipv4 or test_ratelimit_event_ipv6 or test_ratelimit_event_provider or test_ratelimit_event_tag or test_ratelimit_event_company or test_ratelimit_event_country or test_logs or test_ip_asn or test_geo or test_ipv6 or test_ratelimit_scope_path_include or test_ratelimit_scope_path_include_exclud or test_ratelimit_scope_uri_include or test_ratelimit_scope_uri_include_exclud or test_ratelimit_scope_method_include or test_ratelimit_scope_method_exclude or test_ratelimit_scope_query_include or test_ratelimit_scope_query_exclude or test_ratelimit_scope_authority_include or test_ratelimit_scope_authority_exclude or test_ratelimit_countby_ipv6 or test_ratelimit_countby_uri or test_ratelimit_countby_path or test_ratelimit_countby_query or test_ratelimit_countby_method or test_ratelimit_countby_authority or test_ratelimit_event_uri or test_ratelimit_event_path or test_ratelimit_event_query or test_ratelimit_event_method or test_ratelimit_event_authority or test_ipv6 or test_country or test_asn or test_ratelimit_scope_include or test_ratelimit_scope_include_exclude or test_ratelimit_scope_exclude or test_ratelimit_countby_section or test_ratelimit_countby2_section or test_ratelimit_countby_2sections or test_ratelimit_event_section or test_length_overlong or test_length_short or test_count_few or test_count_toomany or test_allowlisted_value or test_allowlisted_value or test_allowlisted_value or test_allowlisted_value or test_allowlisted_value or test_allowlisted_value or test_allowlisted_value or test_allowlisted_value or test_non_allowlisted_value_restrict or test_non_allowlisted_value_norestrict_nowafmatch or test_non_allowlisted_value_norestrict_wafmatch or test_non_allowlisted_value_norestrict_wafmatch_excludesig or test_allowlisted_value or test_allowlisted_value or test_non_allowlisted_value_restrict or test_non_allowlisted_value_norestrict_nowafmatch or test_non_allowlisted_value_norestrict_wafmatch or test_non_allowlisted_value_norestrict_wafmatch_excludesig)' .

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@ea8720de4a2e723f8204d44fc0178744cf401c1a
        with:
          files: e2e/pytest.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: E2E Test Results on docker-compose
          comment_title: E2E Test Statistics
          hide_comments: all but latest
          comment_on_pr: true
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
        if: >
          always() &&
          github.event.sender.login != 'dependabot[bot]' &&
          ( github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository )

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: |
            e2e/pytest.xml
